# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160909_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-create_date',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
